# Generated by Django 5.0.7 on 2024-10-19 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20241019_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='salon',
        ),
    ]
