# Generated by Django 5.0.7 on 2024-10-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
