# Generated by Django 5.0.7 on 2024-10-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_customer_verification_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
