# Generated by Django 5.0.7 on 2024-10-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_salon_name_salon_full_name_salon_salon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='image',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
