# Generated by Django 5.0.7 on 2024-10-24 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_salon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='haircut_duration',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='image',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='price',
        ),
        migrations.CreateModel(
            name='Haircut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(default=1, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('haircut_duration', models.IntegerField(blank=True, null=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salon')),
            ],
        ),
    ]
