# Generated by Django 5.0.7 on 2024-10-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_salon_haircut_duration_remove_salon_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='haircut',
            old_name='haircut_duration',
            new_name='duration',
        ),
    ]
