# Generated by Django 5.0.7 on 2024-10-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_haircut_duration_haircut_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haircut',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
